### ISSUE TITLE
hide_request_button won't hide button?

### ISSUE THREAD

**Issue by Blake-** [AtlasSystems/ArchivesSpace-Aeon-Fulfillment-Plugin#43]
```
 "repo" => {
    :hide_request_button => true
   },
```

I've tried every variation I can think of to hide the button and it never goes away. There's still a button on that repo
Is that not working or am I missing something?

**Comment by kathryn-gillespie** [comment]
Hi Blake,

Are there multiple repositories in the instance of ASpace you’re configuring? We found in some cases, the button needs to be enabled or disabled for every repository in order for the button to correctly display or hide.

Let me know whether that applies here and if not, we can do some troubleshooting.

Thanks,
Katie

--

Join the Aeon Community Listserv to receive Aeon updates, release information, and messages from other Aeon users. Subscribe here<https://lists.atlas-sys.com/mailman/listinfo/aeoncommunity>!

From: Blake Carver ***@***.***>
Date: Monday, June 3, 2024 at 8:13 PM
To: AtlasSystems/ArchivesSpace-Aeon-Fulfillment-Plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AtlasSystems/ArchivesSpace-Aeon-Fulfillment-Plugin] hide_request_button won't hide button? (Issue #43)

 "repo" => {

    :hide_request_button => true

   },

I've tried every variation I can think of to hide the button and it never goes away. There's still a button on that repo
Is that not working or am I missing something?

**Comment by Blake-** [comment]
@kathryn-gillespie should we see NOTHING when we set hide to true or see " No requestable containers " in place of the button? I was expecting to see nothing there at all.

**Comment by kathryn-gillespie** [comment]
@Blake- you should see nothing in repositories where the button is hidden. Here are 2 examples:

Enabled: https://findingaids.library.northwestern.edu/repositories/7/archival_objects/527561
Hidden: https://findingaids.library.northwestern.edu/repositories/4/archival_objects/385418

**Comment by jbaughman** [comment]
@Blake- Thank you for raising this issue. After examining the code, it looks like the hide_request_button is doing a little more than just that, and it is the reason you're now seeing the "No requestable containers" message instead of the request button. When hiding the request button, the plugin will show some alternative text in some cases; in this situation, there are no top level containers in the collection you're looking at, so it's showing the default 'no containers' message. 

It looks like we could document this functionality better so I'll submit a work item to better define and clarify how the hide button feature works. For now, the "No requestable containers" message can be overridden on the repository level by configuring the :no_containers_message setting to be an empty string.

**Comment by Blake-** [comment]
@jbaughman Thanks!
